updated SnapATAC2 version
broadinstitute/warp-tools pull request #124
Opened 2024-04-25 15:18 UTC by ekiernan

Updated SnapATAC2 to latest version 2.6.0

2024-05-10 17:20 UTC, kevinpalis requested changes
This seems to be a duplicate PR doing overlapping things as https://github.com/broadinstitute/warp-tools/pull/125 - which will result in merge conflicts. Might be worth merging these two feature branches first before merging to develop.

2024-05-10 18:49 UTC, ekiernan commented
> This seems to be a duplicate PR doing overlapping things as #125 - which will result in merge conflicts. Might be worth merging these two feature branches first before merging to develop.

This PR no longer has merge conflicts.

2024-05-10 18:51 UTC, kevinpalis approved these changes

2024-05-20 21:07 UTC, khajoue2 approved these changes

2024-05-23 14:21 UTC, merged